#!/bin/bash
# Path to the local repo.
LOCAL_REPO="/root/localrepo"

# Generate a Packages file.
(cd $LOCAL_REPO ; apt-ftparchive packages . > Packages)

# Update to include any new packages in the local repo.
apt-get update

